**Problem 1: Breast Cancer Classification**

Dataset: https://www.kaggle.com/datasets/uciml/breast-cancer-wisconsin-data

Objective

Predict whether a tumor is:

    Malignant (M)

    Benign (B)

Tasks

1.Load the dataset.

2.Drop unnecessary columns (e.g., id, Unnamed: 32).

3.Convert target labels (M → 1, B → 0).

4.Split the dataset (80/20).

5.Standardize the features.

6.Train an SVM with a Linear Kernel.

7.Evaluate using:

    Accuracy

    Precision

    Recall

In [ ]:
import numpy as np
import pandas as pd


from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler


from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, precision_score, recall_score

In [137]:
df=pd.read_csv('data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [138]:
df.isnull().sum()

id                           0
diagnosis                    0
radius_mean                  0
texture_mean                 0
perimeter_mean               0
area_mean                    0
smoothness_mean              0
compactness_mean             0
concavity_mean               0
concave points_mean          0
symmetry_mean                0
fractal_dimension_mean       0
radius_se                    0
texture_se                   0
perimeter_se                 0
area_se                      0
smoothness_se                0
compactness_se               0
concavity_se                 0
concave points_se            0
symmetry_se                  0
fractal_dimension_se         0
radius_worst                 0
texture_worst                0
perimeter_worst              0
area_worst                   0
smoothness_worst             0
compactness_worst            0
concavity_worst              0
concave points_worst         0
symmetry_worst               0
fractal_dimension_worst      0
Unnamed: 32                569
dtype: int64

In [139]:
df = df.drop(["id", "Unnamed: 32"], axis=1)
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [140]:
df

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,0.2419,...,25.380,17.33,184.60,2019.0,0.16220,0.66560,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,0.1812,...,24.990,23.41,158.80,1956.0,0.12380,0.18660,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,0.2069,...,23.570,25.53,152.50,1709.0,0.14440,0.42450,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,0.2597,...,14.910,26.50,98.87,567.7,0.20980,0.86630,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,0.1809,...,22.540,16.67,152.20,1575.0,0.13740,0.20500,0.4000,0.1625,0.2364,0.07678
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,M,21.56,22.39,142.00,1479.0,0.11100,0.11590,0.24390,0.13890,0.1726,...,25.450,26.40,166.10,2027.0,0.14100,0.21130,0.4107,0.2216,0.2060,0.07115
565,M,20.13,28.25,131.20,1261.0,0.09780,0.10340,0.14400,0.09791,0.1752,...,23.690,38.25,155.00,1731.0,0.11660,0.19220,0.3215,0.1628,0.2572,0.06637
566,M,16.60,28.08,108.30,858.1,0.08455,0.10230,0.09251,0.05302,0.1590,...,18.980,34.12,126.70,1124.0,0.11390,0.30940,0.3403,0.1418,0.2218,0.07820
567,M,20.60,29.33,140.10,1265.0,0.11780,0.27700,0.35140,0.15200,0.2397,...,25.740,39.42,184.60,1821.0,0.16500,0.86810,0.9387,0.2650,0.4087,0.12400
568,B,7.76,24.54,47.92,181.0,0.05263,0.04362,0.00000,0.00000,0.1587,...,9.456,30.37,59.16,268.6,0.08996,0.06444,0.0000,0.0000,0.2871,0.07039

In [141]:
# 3 no
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()

df["diagnosis"] = encoder.fit_transform(df["diagnosis"])

print(encoder.classes_)

['B' 'M']

In [142]:
df['diagnosis']

0      1
1      1
2      1
3      1
4      1
      ..
564    1
565    1
566    1
567    1
568    0
Name: diagnosis, Length: 569, dtype: int64

In [143]:
# 4 no
from sklearn.model_selection import train_test_split

x = df.drop("diagnosis", axis=1)
y = df["diagnosis"]

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42, stratify=y)

In [144]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
x_train=scaler.fit_transform(x_train)
x_test=scaler.transform(x_test)

In [145]:
from sklearn.svm import SVC
SVM_model = SVC(kernel="linear")
SVM_model.fit(x_train, y_train)

SVC(kernel='linear')

In [146]:
y_pred = SVM_model.predict(x_test)

In [147]:
from sklearn.metrics import accuracy_score, precision_score, recall_score
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy :", accuracy)
precision = precision_score(y_test, y_pred)
print("Precision :", precision)
recall = recall_score(y_test, y_pred)
print("Recall :", recall)

Accuracy : 0.9649122807017544
Precision : 1.0
Recall : 0.9047619047619048

সহজ বাংলায়:

### ১. Accuracy (একিউরেসি)

**অর্থ:** মডেল মোট ভবিষ্যদ্বাণীর মধ্যে কতগুলো সঠিকভাবে করেছে।

**সূত্র:**

[
\text{Accuracy}=\frac{TP+TN}{TP+TN+FP+FN}
]

**সহজভাবে:**
মডেলের **সামগ্রিক সঠিকতার হার**।

---

### ২. Precision (প্রিসিশন)

**অর্থ:** মডেল যেগুলোকে **Positive (Malignant)** বলেছে, তার মধ্যে আসলে কতগুলো সত্যিই Positive।

**সূত্র:**

[
\text{Precision}=\frac{TP}{TP+FP}
]

**সহজভাবে:**
মডেল **Positive বললে সেটি কতটা বিশ্বাসযোগ্য**, তা বোঝায়।

---

### ৩. Recall (রিকল)

**অর্থ:** আসল **Positive (Malignant)** রোগীদের মধ্যে মডেল কতজনকে সঠিকভাবে শনাক্ত করতে পেরেছে।

**সূত্র:**

[
\text{Recall}=\frac{TP}{TP+FN}
]

**সহজভাবে:**
মডেল **আসল Positive কেসগুলোর কত শতাংশ ধরতে পেরেছে**, তা বোঝায়।

---


* **Accuracy:** মডেল মোট কত শতাংশ সঠিক Prediction করেছে।
* **Precision:** মডেল যাদের Positive বলেছে, তাদের মধ্যে কত শতাংশ সত্যিই Positive।
* **Recall:** আসল Positive কেসগুলোর মধ্যে মডেল কত শতাংশ সঠিকভাবে শনাক্ত করেছে।

## **question: 4**
Dataset: https://www.kaggle.com/datasets/fedesoriano/heart-failure-prediction
Objective
Predict whether a patient has heart disease.

Tasks

Train four SVM models:

    Linear
    Polynomial
    RBF
    Sigmoid

**Compare**

Accuracy

Precision

Recall

In [148]:
df=pd.read_csv('heart.csv')
df.sample(12)

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
505,55,M,NAP,136,245,1,ST,131,Y,1.2,Flat,1
62,45,M,ASY,140,224,0,Normal,144,N,0.0,Up,0
249,49,M,ASY,130,341,0,Normal,120,Y,1.0,Flat,1
500,65,M,ASY,136,248,0,Normal,140,Y,4.0,Down,1
476,51,M,ASY,132,218,1,LVH,139,N,0.1,Up,0
536,62,M,NAP,133,0,1,ST,119,Y,1.2,Flat,1
650,48,M,ASY,130,256,1,LVH,150,Y,0.0,Up,1
703,41,F,ATA,126,306,0,Normal,163,N,0.0,Up,0
645,57,M,NAP,128,229,0,LVH,150,N,0.4,Flat,1
205,50,M,ASY,150,215,0,Normal,140,Y,0.0,Up,0
242,55,M,ATA,160,292,1,Normal,143,Y,2.0,Flat,1
660,58,M,NAP,140,211,1,LVH,165,N,0.0,Up,0

In [149]:
df.isnull().sum()

Age               0
Sex               0
ChestPainType     0
RestingBP         0
Cholesterol       0
FastingBS         0
RestingECG        0
MaxHR             0
ExerciseAngina    0
Oldpeak           0
ST_Slope          0
HeartDisease      0
dtype: int64

In [150]:
X = df.drop("HeartDisease", axis=1)
y = df["HeartDisease"]

In [151]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42
)

In [152]:
categorical_columns = X.select_dtypes(include="object").columns

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

preprocessor = ColumnTransformer(
    transformers=[
        (
          "cat",OneHotEncoder(handle_unknown="ignore"),categorical_columns
        )
    ],
    remainder="passthrough"
)

In [153]:
X_train_encoded = preprocessor.fit_transform(X_train)

In [154]:
from sklearn.pipeline import Pipeline
from sklearn.svm import SVC

SVC_model = Pipeline(
    steps=[
        ("preprocessor", preprocessor),
        ("model", SVC())
    ]
)

In [155]:
grid_param = [
    {
        "model__kernel": ["linear"],
        "model__C": [0.01, 0.1, 1, 10, 50, 100]
    },
    {
        "model__kernel": ["poly"],
        "model__C": [0.01, 0.1, 1, 10, 100],
        "model__degree": [2, 3]
    },
    {
        "model__kernel": ["rbf"],
        "model__C": [0.01, 0.1, 1, 10, 100],
        "model__gamma": [0.01, 0.1, 5, 10, "scale", "auto"]
    },
    {
        "model__kernel": ["sigmoid"],
        "model__C": [0.01, 0.1, 1, 10, 100],
        "model__gamma": [0.01, 0.1, "scale", "auto"]
    }
]

In [156]:
from sklearn.model_selection import GridSearchCV

best_SVC_model = GridSearchCV(
    estimator=SVC_model,
    param_grid=grid_param,
    cv=5,
    scoring="accuracy"
)
best_SVC_model.fit(X_train, y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/compose/_column_transformer.py:1667: FutureWarning:
The format of the columns of the 'remainder' transformer in ColumnTransformer.transformers_ will change in version 1.7 to match the format of the other transformers.
At the moment the remainder columns are stored as indices (of type int). With the same ColumnTransformer configuration, in the future they will be stored as column names (of type str).
To use the new behavior now and suppress this warning, use ColumnTransformer(force_int_remainder_cols=False).

  warnings.warn(

GridSearchCV(cv=5,
             estimator=Pipeline(steps=[('preprocessor',
                                        ColumnTransformer(remainder='passthrough',
                                                          transformers=[('cat',
                                                                         OneHotEncoder(handle_unknown='ignore'),
                                                                         Index(['Sex', 'ChestPainType', 'RestingECG', 'ExerciseAngina', 'ST_Slope'], dtype='object'))])),
                                       ('model', SVC())]),
             param_grid=[{'model__C': [0.01, 0.1, 1, 10, 50, 100],
                          'model__kernel': ['linear']},
                         {'model__C': [0.01, 0.1, 1, 10, 100],
                          'model__degree': [2, 3], 'model__kernel': ['poly']},
                         {'model__C': [0.01, 0.1, 1, 10, 100],
                          'model__gamma': [0.01, 0.1, 5, 10, 'scale', 'auto'],
                          'model__kernel': ['rbf']},
                         {'model__C': [0.01, 0.1, 1, 10, 100],
                          'model__gamma': [0.01, 0.1, 'scale', 'auto'],
                          'model__kernel': ['sigmoid']}],
             scoring='accuracy')

In [157]:
print(best_SVC_model.best_params_)
print(best_SVC_model.best_score_)

{'model__C': 10, 'model__kernel': 'linear'}
0.8719131488211722

In [ ]:
y_pred = best_SVC_model.predict(X_test)


from sklearn.metrics import accuracy_score, precision_score, recall_score


print("Accuracy :", accuracy_score(y_test, y_pred))
print("Precision :", precision_score(y_test, y_pred))
print("Recall :", recall_score(y_test, y_pred))

Accuracy : 0.8641304347826086
Precision : 0.9019607843137255
Recall : 0.8598130841121495

# **Problem 5:**

 Customer Churn Prediction
Dataset: https://www.kaggle.com/datasets/blastchar/telco-customer-churn

Objective
Predict whether a customer will churn.

**Tasks**

1.Handle missing values.

2.Encode categorical columns.

3.Scale numerical columns.

4.Train SVM.

5.Tune hyperparameters.

In [159]:
df=pd.read_csv("WA_Fn-UseC_-Telco-Customer-Churn.csv")
df.sample(12)

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
3058,2858-MOFSQ,Female,0,No,Yes,17,Yes,Yes,DSL,No,...,Yes,No,No,No,One year,Yes,Mailed check,55.85,937.5,Yes
4543,7216-KAOID,Male,0,Yes,Yes,41,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,One year,No,Bank transfer (automatic),19.50,798.2,No
3221,5960-MVTUK,Male,0,No,No,3,No,No phone service,DSL,No,...,No,Yes,No,No,Month-to-month,Yes,Electronic check,29.75,96.85,No
7036,7750-EYXWZ,Female,0,No,No,12,No,No phone service,DSL,No,...,Yes,Yes,Yes,Yes,One year,No,Electronic check,60.65,743.3,No
6571,2188-SXWVT,Female,0,No,No,34,Yes,No,DSL,Yes,...,No,No,No,No,One year,No,Mailed check,55.00,1885.15,No
2517,5186-SAMNZ,Male,1,No,No,1,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Bank transfer (automatic),69.50,69.5,Yes
1638,8883-ANODQ,Female,0,Yes,Yes,68,Yes,Yes,Fiber optic,No,...,Yes,No,No,No,Two year,Yes,Credit card (automatic),84.40,5746.75,No
4133,2208-UGTGR,Male,0,No,No,56,Yes,Yes,Fiber optic,No,...,No,No,Yes,Yes,Month-to-month,No,Electronic check,98.60,5581.05,No
2866,7517-LDMPS,Female,0,No,No,12,Yes,No,Fiber optic,No,...,No,No,No,Yes,Month-to-month,Yes,Electronic check,84.60,1017.35,No
5692,3948-FVVRP,Male,0,Yes,Yes,9,Yes,No,DSL,No,...,No,Yes,No,No,Month-to-month,No,Mailed check,54.80,452.8,No
1956,0019-EFAEP,Female,0,No,No,72,Yes,Yes,Fiber optic,Yes,...,Yes,No,Yes,No,Two year,Yes,Bank transfer (automatic),101.30,7261.25,No
5303,9839-ETQOE,Male,0,No,Yes,43,No,No phone service,DSL,Yes,...,Yes,No,No,No,Month-to-month,Yes,Electronic check,40.45,1912.85,No

In [160]:
df.isnull().sum()

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [161]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42
)

In [162]:
categorical_columns = X_train.select_dtypes(include="object").columns

numerical_columns = X_train.select_dtypes(exclude="object").columns
preprocessor = ColumnTransformer(
    transformers=[
        (
          "cat",OneHotEncoder(handle_unknown="ignore"),categorical_columns
        ),
        (
          "num",StandardScaler(),numerical_columns
        )
    ],
    remainder="passthrough"
)

In [163]:
from sklearn.pipeline import Pipeline
from sklearn.svm import SVC

SVC_model = Pipeline(
    steps=[
        ("preprocessor",preprocessor),
        ("model",SVC())
    ]
)
SVC_model

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('cat',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  Index(['Sex', 'ChestPainType', 'RestingECG', 'ExerciseAngina', 'ST_Slope'], dtype='object')),
                                                 ('num', StandardScaler(),
                                                  Index(['Age', 'RestingBP', 'Cholesterol', 'FastingBS', 'MaxHR', 'Oldpeak'], dtype='object'))])),
                ('model', SVC())])

In [164]:
grid_param=[
    {
        "model__kernel":["linear"],
        "model__C":[0.01,0.1,1,10,12,23,100]
    },
    {
        "model__kernel":["rbf"],
        "model__C":[0.01,0.1,1,6,7,10],
        "model__gamma":[0.01,0.1,"scale","auto"]
    },
    {
        "model__kernel":["poly"],
        "model__C":[0.01,0.1,1,3,4,6,10],
        "model__degree":[2,3]
    },
    {
        "model__kernel":["sigmoid"],
        "model__C":[0.01,0.1,1,3,4,5,10],
        "model__gamma":[0.01,0.1,"scale","auto"]
    }
]

In [165]:
from sklearn.model_selection import GridSearchCV

best_SVC_model=GridSearchCV(
    estimator=SVC_model,
    param_grid=grid_param,
    cv=5
)

In [166]:
best_SVC_model.fit(X_train,y_train)

GridSearchCV(cv=5,
             estimator=Pipeline(steps=[('preprocessor',
                                        ColumnTransformer(remainder='passthrough',
                                                          transformers=[('cat',
                                                                         OneHotEncoder(handle_unknown='ignore'),
                                                                         Index(['Sex', 'ChestPainType', 'RestingECG', 'ExerciseAngina', 'ST_Slope'], dtype='object')),
                                                                        ('num',
                                                                         StandardScaler(),
                                                                         Index(['Age', 'RestingBP', 'Cholesterol', 'FastingBS', 'MaxHR', 'Oldpeak'], dtype=...
             param_grid=[{'model__C': [0.01, 0.1, 1, 10, 12, 23, 100],
                          'model__kernel': ['linear']},
                         {'model__C': [0.01, 0.1, 1, 6, 7, 10],
                          'model__gamma': [0.01, 0.1, 'scale', 'auto'],
                          'model__kernel': ['rbf']},
                         {'model__C': [0.01, 0.1, 1, 3, 4, 6, 10],
                          'model__degree': [2, 3], 'model__kernel': ['poly']},
                         {'model__C': [0.01, 0.1, 1, 3, 4, 5, 10],
                          'model__gamma': [0.01, 0.1, 'scale', 'auto'],
                          'model__kernel': ['sigmoid']}])

In [167]:
print(best_SVC_model.best_params_)

{'model__C': 1, 'model__gamma': 'auto', 'model__kernel': 'rbf'}

In [168]:
from sklearn.metrics import accuracy_score,precision_score,recall_score,f1_score

print("Precision :", precision_score(y_test, y_pred))
print("Recall :", recall_score(y_test, y_pred))
print("F1 Score :", f1_score(y_test, y_pred))

Precision : 0.9019607843137255
Recall : 0.8598130841121495
F1 Score : 0.8803827751196173

# **question :6**

Dataset: https://www.kaggle.com/datasets/mlg-ulb/creditcardfraud

Objective

Detect fraudulent transactions.

# Tasks

Handle imbalanced data. ( there is a parameter in SVC to address this )

Train SVM.

Use:

Precision

Recall

F1-score

In [169]:
df=pd.read_csv("creditcard.csv")
df.sample(12)

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
142906,85009.0,-1.009890,1.138252,1.237909,0.861849,0.092237,-0.261061,0.556504,0.114137,-0.641934,...,0.108762,0.322035,-0.354499,0.098969,0.477620,-0.215094,-0.506640,-0.330995,28.98,0
228000,145317.0,1.891008,-0.924756,-0.692881,0.556635,-0.732237,0.025983,-0.677927,0.057985,-0.417289,...,-0.241542,-0.299816,0.141170,-0.550487,-0.211368,-0.668391,0.047044,-0.031152,93.00,0
230568,146385.0,-2.760580,1.038115,-0.205750,-0.326014,5.540139,-3.335734,-9.083432,-9.011899,1.210209,...,4.757494,-3.505226,-9.235885,0.306621,-1.459422,-0.218724,0.819292,0.640904,0.00,0
62431,50263.0,1.154798,0.108880,0.512783,1.480946,-0.460226,-0.412225,-0.057662,0.068910,0.543866,...,-0.105724,-0.140956,0.006568,0.370992,0.561156,-0.326141,0.029853,0.014164,1.00,0
53089,45810.0,-0.859089,0.126575,0.831417,-1.073587,1.244260,4.607128,0.111803,0.694545,0.548709,...,-0.299971,-0.533870,-0.299493,1.104930,0.021091,1.078849,-0.414400,-0.190753,151.94,0
122212,76476.0,1.320388,0.163277,0.143575,0.432431,-0.154232,-0.535670,-0.020387,-0.098740,0.243727,...,-0.323831,-0.974676,0.044813,-0.486334,0.298149,0.149813,-0.036078,0.008357,0.89,0
40018,40060.0,1.228473,-0.138826,0.473795,-0.166381,-0.453564,-0.190135,-0.355309,0.048598,0.128943,...,-0.172147,-0.574730,0.036834,-0.303782,0.073315,0.810356,-0.069178,0.001890,25.57,0
230111,146191.0,-1.604118,-1.518815,0.361063,-0.163143,-1.712897,1.923865,2.225327,-0.653971,1.471703,...,-0.234855,1.431418,0.907946,-0.957934,-0.590781,-0.263348,0.472978,-0.566972,553.56,0
60652,49427.0,-0.996102,-5.201781,-1.471678,-0.325655,-2.488683,-0.097595,0.866767,-0.429344,-2.059837,...,0.595684,-0.792962,-1.270244,0.052876,0.182907,-0.195941,-0.239213,0.219517,1311.12,0
5176,4927.0,-1.222515,1.319420,0.851871,1.652785,-1.345659,0.600803,1.350940,0.109842,0.799709,...,-0.163682,0.174470,-0.054990,0.401030,-0.134560,-0.299316,0.209672,0.013097,278.15,0
265004,161687.0,-0.281890,-0.039618,-0.759138,-1.985531,1.240182,-1.308066,0.980647,-0.275082,-1.953747,...,0.634603,1.567972,-0.443512,0.819854,0.505363,0.204709,0.028001,0.124681,20.00,0
149711,91777.0,0.184402,2.072151,-2.564644,-0.244701,2.077772,-2.389089,2.057487,-0.998766,1.660118,...,-0.357485,-0.041923,-0.257406,-0.419296,-0.111408,0.016869,0.137258,-0.198167,8.67,0

In [170]:
df.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

In [171]:
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.compose import ColumnTransformer


numerical_columns = df.select_dtypes(exclude="object").columns
numerical_columns

Index(['Time', 'V1', 'V2', 'V3', 'V4', 'V5', 'V6', 'V7', 'V8', 'V9', 'V10',
       'V11', 'V12', 'V13', 'V14', 'V15', 'V16', 'V17', 'V18', 'V19', 'V20',
       'V21', 'V22', 'V23', 'V24', 'V25', 'V26', 'V27', 'V28', 'Amount',
       'Class'],
      dtype='object')

In [172]:
numerical_pipeline=(
    [
        ("imputer",SimpleImputer(strategy="mean")),
        ("scaler",StandardScaler())
    ]
)
prepocssor= ColumnTransformer(
    transformers=[
        ("num",numerical_pipeline,numerical_columns)
    ]
)

In [173]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42
)

In [174]:
SVC_model = Pipeline(
    steps=[
        ("preprocessor",preprocessor),
        ("model",SVC())
    ]
)

In [181]:
grid_param=[
    {
    "model__kernel":["linear"],
    "model__C":[0.01,0.1,1,2,3,4,5,10]
    },
    {
    "model__kernel":["rbf"],
    "model__C":[0.01,0.1,1,2,3,4,5,10],
    "model__gamma":[0.01,0.1,"scale","auto"]
    },
    {
    "model__kernel":["poly"],
    "model__C":[0.01,0.1,1,2,3,4,5,10],
    "model__degree":[2,3,4,6,7]
    }

]

In [182]:
from sklearn.model_selection import GridSearchCV

best_SVC_model=GridSearchCV(
    estimator=SVC_model,
    param_grid=grid_param,
    cv=5
)

In [183]:
best_SVC_model.fit(X_train,y_train)

GridSearchCV(cv=5,
             estimator=Pipeline(steps=[('preprocessor',
                                        ColumnTransformer(remainder='passthrough',
                                                          transformers=[('cat',
                                                                         OneHotEncoder(handle_unknown='ignore'),
                                                                         Index(['Sex', 'ChestPainType', 'RestingECG', 'ExerciseAngina', 'ST_Slope'], dtype='object')),
                                                                        ('num',
                                                                         StandardScaler(),
                                                                         Index(['Age', 'RestingBP', 'Cholesterol', 'FastingBS', 'MaxHR', 'Oldpeak'], dtype='object'))])),
                                       ('model', SVC())]),
             param_grid=[{'model__C': [0.01, 0.1, 1, 2, 3, 4, 5, 10],
                          'model__kernel': ['linear']},
                         {'model__C': [0.01, 0.1, 1, 2, 3, 4, 5, 10],
                          'model__gamma': [0.01, 0.1, 'scale', 'auto'],
                          'model__kernel': ['rbf']},
                         {'model__C': [0.01, 0.1, 1, 2, 3, 4, 5, 10],
                          'model__degree': [2, 3, 4, 6, 7],
                          'model__kernel': ['poly']}])

In [184]:
y_pred=best_SVC_model.predict(X_test)

In [185]:
from sklearn.metrics import accuracy_score,precision_score,recall_score

print("Precision :", precision_score(y_test, y_pred))
print("Recall :", recall_score(y_test, y_pred))
print("F1 Score :", f1_score(y_test, y_pred))

Precision : 0.8857142857142857
Recall : 0.8691588785046729
F1 Score : 0.8773584905660378


#important note

 এই `grid_param`-টাই হলো **GridSearchCV-এর সবচেয়ে গুরুত্বপূর্ণ অংশ**। এখানে Model-কে বলছো **কোন কোন Parameter-এর Combination পরীক্ষা করতে হবে**।

তবে আগে একটা ছোট ভুল আছে। তুমি `;` (semicolon) ব্যবহার করেছ, Python-এ এখানে `,` (comma) হবে।

সঠিক কোড:

```python
grid_param = [
    {
        "model__kernel": ["linear"],
        "model__C": [0.01, 0.1, 1, 2, 3, 4, 5, 10]
    },
    {
        "model__kernel": ["rbf"],
        "model__C": [0.01, 0.1, 1, 2, 3, 4, 5, 10],
        "model__gamma": [0.01, 0.1, "scale", "auto"]
    },
    {
        "model__kernel": ["poly"],
        "model__C": [0.01, 0.1, 1, 2, 3, 4, 5, 10],
        "model__degree": [2, 3, 4, 6, 7]
    }
]
```

---

## `grid_param = []` কেন List?

কারণ তুমি **একাধিক Kernel** পরীক্ষা করছো।

* ১ম Dictionary → Linear
* ২য় Dictionary → RBF
* ৩য় Dictionary → Polynomial

---

## ১ম Dictionary

```python
{
    "model__kernel": ["linear"],
    "model__C": [0.01, 0.1, 1, 2, 3, 4, 5, 10]
}
```

এর মানে:

GridSearchCV নিচের Model-গুলো চালাবে:

```text
Linear + C = 0.01
Linear + C = 0.1
Linear + C = 1
Linear + C = 2
...
Linear + C = 10
```

মোট **৮টি Model**।

---

## `C` কী?

`C` হলো **Regularization Parameter**।

* **C ছোট** (0.01, 0.1)

  * Model সহজ (Simple)
  * কিছু ভুল মেনে নেয়
  * Overfitting কম হয়

* **C বড়** (10, 100)

  * ভুল কম করতে চায়
  * Training Data ভালোভাবে Fit করে
  * Overfitting হতে পারে

---

## ২য় Dictionary (RBF)

```python
{
    "model__kernel": ["rbf"],
    "model__C": [...],
    "model__gamma": [...]
}
```

এখানে GridSearchCV **C** এবং **gamma**-এর সব Combination পরীক্ষা করবে।

উদাহরণ:

```text
RBF + C=0.01 + gamma=0.01
RBF + C=0.01 + gamma=0.1
RBF + C=0.01 + gamma=scale
RBF + C=0.01 + gamma=auto

RBF + C=0.1 + gamma=0.01
...
```

যদি

* `C` = 8টি মান
* `gamma` = 4টি মান

তাহলে

**8 × 4 = 32টি Model** ট্রাই করবে।

---

## `gamma` কী?

`gamma` শুধু **RBF**, **Poly**, **Sigmoid** Kernel-এ কাজ করে।

* **gamma ছোট** → দূরের Point-ও প্রভাব ফেলে → Boundary মসৃণ।
* **gamma বড়** → কাছের Point বেশি প্রভাব ফেলে → Boundary জটিল হতে পারে।

---

## ৩য় Dictionary (Polynomial)

```python
{
    "model__kernel": ["poly"],
    "model__C": [...],
    "model__degree": [2,3,4,6,7]
}
```

এখানে

* `degree = 2` → Quadratic
* `degree = 3` → Cubic
* `degree = 4` → Fourth-degree polynomial

যদি

* `C` = 8টি
* `degree` = 5টি

তাহলে

**8 × 5 = 40টি Model** পরীক্ষা করবে।

---

## GridSearchCV কীভাবে Best Model বের করে?

ধরো সে মোট **80টি Model** ট্রেন করল।

তারপর প্রতিটির **Cross Validation Score** বের করবে।

যেটার Score সবচেয়ে বেশি, সেটাই হবে:

```python
best_SVC_model.best_params_
```

যেমন:

```python
{'model__kernel': 'linear',
 'model__C': 10}
```

অর্থাৎ GridSearchCV বলছে:

> **সব Combination-এর মধ্যে `Linear Kernel` এবং `C = 10` সবচেয়ে ভালো ফল দিয়েছে।**

এটাই `best_params_`-এর অর্থ।





# ১. `degree` কী? (শুধু Polynomial Kernel-এর জন্য)

`degree` মানে **Curve কতটা বাঁকা (complex) হবে**।

* `degree = 2` → একটু বাঁকা
* `degree = 3` → আরও বাঁকা
* `degree = 4` → আরও জটিল
* `degree` যত বাড়বে → Model তত জটিল Pattern শিখতে পারবে।

**সহজ উদাহরণ:**

* `degree = 2` → 😊 (হালকা বাঁক)
* `degree = 7` → 🌀 (অনেক বেশি বাঁক)

যদি Data খুব জটিল হয়, বড় `degree` কাজে আসতে পারে। কিন্তু খুব বড় `degree` দিলে **Overfitting** হতে পারে।

---

# ২. `gamma` কী? (RBF, Poly, Sigmoid-এর জন্য)

`gamma` ঠিক করে **একটি Data Point তার আশেপাশে কতটা প্রভাব ফেলবে**।

### `gamma` ছোট

```text
gamma = 0.01
```

একটি Point দূরের Point-কেও প্রভাবিত করে।

➡️ Boundary মসৃণ (Smooth) হয়।

---

### `gamma` বড়

```text
gamma = 10
```

একটি Point শুধু খুব কাছের Point-কে প্রভাবিত করে।

➡️ Boundary অনেক জটিল (Complex) হয়।

---

## সহজ ট্রিক

### `degree`

> **degree = Curve-এর বাঁক কতটা হবে।**

* ছোট degree → সহজ Curve
* বড় degree → জটিল Curve

---

### `gamma`

> **gamma = একটি Point-এর প্রভাব কত দূর পর্যন্ত যাবে।**

* ছোট gamma → প্রভাব দূর পর্যন্ত যায়।
* বড় gamma → প্রভাব শুধু কাছাকাছি থাকে।

---

## পরীক্ষার জন্য এক লাইনে

* **Degree:** Polynomial Kernel-এর Curve-এর জটিলতা নির্ধারণ করে।
* **Gamma:** একটি Training Point-এর প্রভাব কত দূর পর্যন্ত থাকবে তা নির্ধারণ করে।

এভাবেই লিখলে পরীক্ষায়ও নম্বর পাওয়া যাবে এবং GridSearchCV-তে `degree` ও `gamma` কেন টিউন করা হয় সেটাও বুঝতে সুবিধা হবে।